<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Sli\AuxBundle\SliAuxBundle::class => ['all' => true],
    Sli\ExpanderBundle\SliExpanderBundle::class => ['all' => true],
    Sli\ExtJsIntegrationBundle\SliExtJsIntegrationBundle::class => ['all' => true],
    Knp\Bundle\GaufretteBundle\KnpGaufretteBundle::class => ['all' => true],
    Modera\ActivityLoggerBundle\ModeraActivityLoggerBundle::class => ['all' => true],
    Modera\ConfigBundle\ModeraConfigBundle::class => ['all' => true],
    Modera\DirectBundle\ModeraDirectBundle::class => ['all' => true],
    Modera\DynamicallyConfigurableAppBundle\ModeraDynamicallyConfigurableAppBundle::class => ['all' => true],
    Modera\FileRepositoryBundle\ModeraFileRepositoryBundle::class => ['all' => true],
    Modera\FileUploaderBundle\ModeraFileUploaderBundle::class => ['all' => true],
    Modera\FoundationBundle\ModeraFoundationBundle::class => ['all' => true],
    Modera\LanguagesBundle\ModeraLanguagesBundle::class => ['all' => true],
    Modera\ModuleBundle\ModeraModuleBundle::class => ['all' => true],
    Modera\RoutingBundle\ModeraRoutingBundle::class => ['all' => true],
    Modera\SecurityBundle\ModeraSecurityBundle::class => ['all' => true],
    Modera\ServerCrudBundle\ModeraServerCrudBundle::class => ['all' => true],
    Modera\TranslationsBundle\ModeraTranslationsBundle::class => ['all' => true],
    Modera\MjrIntegrationBundle\ModeraMjrIntegrationBundle::class => ['all' => true],
    Modera\DynamicallyConfigurableMJRBundle\ModeraDynamicallyConfigurableMJRBundle::class => ['all' => true],
    Modera\MJRCacheAwareClassLoaderBundle\ModeraMJRCacheAwareClassLoaderBundle::class => ['all' => true],
    Modera\MJRSecurityIntegrationBundle\ModeraMJRSecurityIntegrationBundle::class => ['all' => true],
    Modera\MJRThemeIntegrationBundle\ModeraMJRThemeIntegrationBundle::class => ['all' => true],
    Modera\BackendConfigUtilsBundle\ModeraBackendConfigUtilsBundle::class => ['all' => true],
    Modera\BackendDashboardBundle\ModeraBackendDashboardBundle::class => ['all' => true],
    Modera\BackendLanguagesBundle\ModeraBackendLanguagesBundle::class => ['all' => true],
    Modera\BackendSecurityBundle\ModeraBackendSecurityBundle::class => ['all' => true],
    Modera\BackendToolsActivityLogBundle\ModeraBackendToolsActivityLogBundle::class => ['all' => true],
    Modera\BackendToolsBundle\ModeraBackendToolsBundle::class => ['all' => true],
    Modera\BackendToolsSettingsBundle\ModeraBackendToolsSettingsBundle::class => ['all' => true],
    Modera\BackendTranslationsToolBundle\ModeraBackendTranslationsToolBundle::class => ['all' => true],
];
