imports:
    - { resource: parameters.yml }
    - { resource: modera.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: '@ModeraSecurityBundle/Resources/config/pdo_session_storage.yml' }

parameters:
    locale: en

framework:
    #esi: ~
    translator:
        fallbacks: ['%locale%']
        default_path: '%kernel.project_dir%/app/Resources/translations'
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: session.handler.pdo
        #gc_maxlifetime: 1440
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

#sensio_framework_extra:
#   router:
#        annotations: false

knp_gaufrette:
    adapters:
        default:
            local:
                directory: '%kernel.root_dir%/../web/uploads'
    filesystems:
        local_fs: #BC
            adapter: default
        default_fs:
            adapter: default
