modera_direct:
    routes_prefix: /backend

modera_file_uploader:
    is_enabled: true
    url: /backend/uploader-gateway

modera_mjr_integration:
    # If you want to have a local copy of ExtJs, you can uncomment the following line:
    #extjs_path: '/extjs'
    viewport_class: 'MF.theme.authenticationaware.Viewport'
    main_config_provider: 'modera_dynamically_configurable_mjr.mjr.main_config'

knp_gaufrette:
    adapters:
        default:
            local:
                directory: '%kernel.project_dir%/public/uploads'
    filesystems:
        default_fs:
            adapter: default
