imports:
    - { resource: '@ModeraSecurityBundle/Resources/config/security.yml' }

modera_security:
    switch_user: true
    access_control:
        - { path: ^/backend/.+, roles: ROLE_BACKEND_USER }

security:
    always_authenticate_before_granting: true
